server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:product;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
